name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Web Tool Updates'
    label: 'web-tool'
  - title: 'Data Processing'
    label: 'data'
  - title: 'Documentation'
    label: 'documentation'

change-template: '- $TITLE @$AUTHOR ([#$NUMBER]($URL))'
change-title-escapes: '\<*_&#@'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: patch
exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
template: |
  ## Release v$RESOLVED_VERSION (v20YY.MM.V)
  $CHANGES
