repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
        language_version: system
        additional_dependencies:
          - 'prettier@2.5.1'
          - '@carbonplan/prettier@1.2.0'
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |html\
          |js|jsx\
          |json\
          |ts|tsx\
          |vue\
          |yaml|yml\
          )$"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
        language_version: system
        additional_dependencies:
          - 'prettier@2.5.1'
          - '@carbonplan/prettier@1.2.0'
        name: prettier-markdown
        entry: prettier --write --parser mdx
        files: "\\.(\
          |md|markdown|mdown|mkdn\
          |mdx\
          )$"
