name: cdr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fsspec
  - jupyter
  - numpy
  - oauth2client
  - google-api-python-client
  - pandas
  - pip
  - pre-commit
  - pytest
  - tabulate
  - s3fs
  - ujson
  - xarray
