name: validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  steps:
    - uses: actions/checkout@v3

    - name: Create conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        micromamba-version: 'latest'
        environment-file: ci/environment.yml
        extra-specs: |
          python=3.10

    - name: Conda info
      run: conda info

    - name: Run Validation
      run: |
        python scripts/postprocess.py
