name: validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Create conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          micromamba-version: 'latest'
          environment-file: ci/environment.yml
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Conda info
        run: conda info

      # - name: install
      #   run: |
      #     python -m pip install --no-deps .

      - name: run-script
        run: |
          python src/validation.py
