name: validation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    permissions:
      contents: 'read'
      id-token: 'write'

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/836213457414/locations/global/workloadIdentityPools/github-actions-google-sheets/providers/github'
          service_account: 'google-sheets@carbonplan.iam.gserviceaccount.com'

      # Install Micromamba with conda-forge dependencies
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1.4.3
        with:
          environment-name: cdr
          init-shell: >-
            bash
          condarc: |
            channels:
              - conda-forge
              - nodefaults
          cache-downloads: true
          cache-environment: true
          create-args: >-
            python=3.10
            fsspec
            jupyter
            tabulate
            numpy
            oauth2client
            google-api-python-client
            pandas
            pip
            pre-commit
            s3fs
            ujson
            xarray

      - name: Run test
        run: |
          python -u scripts/postprocess.py
        shell: bash -el {0}
